# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazytuck" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "29ca3b4d2e257a44ceb801d35f63bfb0c48b59098cd0ab57f961bdf6b7701bfd"
      url "https://github.com/t1mdotcom/lazytuck/releases/download/v#{version}/lazytuck_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e82e10dc3460183fe9f33a743dc8ce8a211f7495ed858f9054978a2cace7162b"
      url "https://github.com/t1mdotcom/lazytuck/releases/download/v#{version}/lazytuck_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6c19efc85fd6f8bf65d5323339de26a5f26654391444d0655c3b7025f4571d0c"
      url "https://github.com/t1mdotcom/lazytuck/releases/download/v#{version}/lazytuck_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c678e5bc64a9d3a71a434ef18df841392bf2abeb225c52d5b10bc78ff947f2b"
      url "https://github.com/t1mdotcom/lazytuck/releases/download/v#{version}/lazytuck_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazytuck"
  desc "lazygit-style TUI for Tuckr dotfile repos"
  homepage "https://github.com/t1mdotcom/lazytuck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazytuck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazytuck"]
    end
  end

  # No zap stanza required
end
