# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazytuck" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "34296ebb1acabe2991fe4e8daf7a30fa52f80b7184f4998b6fd1fd6ba79ca337"
      url "https://github.com/t1mdotcom/lazytuck/releases/download/v#{version}/lazytuck_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa23caeae6660017badf0ac01a4848d4d252795a66d7cffbee2010b0da548141"
      url "https://github.com/t1mdotcom/lazytuck/releases/download/v#{version}/lazytuck_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7e07a3e5105a9c995b92d96fa185d1060a59fbc2f2da189953f1846d33a8bc8a"
      url "https://github.com/t1mdotcom/lazytuck/releases/download/v#{version}/lazytuck_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d0b7e5cc971bcc3816f1f9c052b5416018960a4e45fb6867e573c88a1928d63f"
      url "https://github.com/t1mdotcom/lazytuck/releases/download/v#{version}/lazytuck_#{version}_linux_amd64.tar.gz"
    end
  end

  name "lazytuck"
  desc "lazygit-style TUI for Tuckr dotfile repos"
  homepage "https://github.com/t1mdotcom/lazytuck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazytuck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazytuck"]
    end
  end

  # No zap stanza required
end
